displayName=GOTR Autopilot
author=FabulousOtter
description=Tells you exactly what to do next in Guardians of the Rift
tags=gotr,guardians of the rift,runecraft,minigame
version=1.0.2
plugins=com.fabulousotter.gotr.GotrAutopilotPlugin
build=standard
